sudo: required
dist: trusty

language: go

go:
  - 1.8

env:
  - HYPER_EXEC_DRIVER=qemu    HYPER_STORAGE_DRIVER=aufs
  - HYPER_EXEC_DRIVER=qemu    HYPER_STORAGE_DRIVER=rawblock
  - HYPER_EXEC_DRIVER=libvirt HYPER_STORAGE_DRIVER=overlay
  - HYPER_EXEC_DRIVER=libvirt HYPER_STORAGE_DRIVER=rawblock

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev qemu libvirt-bin aufs-tools -qq
  - cd `mktemp -d`
  - mkdir -p ${GOPATH}/src/github.com/hyperhq
  - wget ftp://sources.redhat.com/pub/lvm2/LVM2.2.02.131.tgz
  - tar xf LVM2.2.02.131.tgz
  - cd LVM2.2.02.131
  - ./configure > /dev/null && make device-mapper > /dev/null && sudo make install > /dev/null

# override the default `install`, otherwise default `install` will export ${TRAVIS_BUILD_DIR}/Godeps/_workspace as GOPATH
# see https://docs.travis-ci.com/user/languages/go#Dependency-Management

install:
  - cd ${TRAVIS_BUILD_DIR}
  - hack/install-grpc.sh
  - hack/verify-gofmt.sh
  - hack/verify-generated-proto.sh
  - ./autogen.sh && ./configure && make

script:
  - cd ${TRAVIS_BUILD_DIR} && hack/test-cmd.sh
