sudo: required
dist: trusty

language: go

matrix:
  include:
    - go: 1.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf automake pkg-config libdevmapper-dev libsqlite3-dev libvirt-dev qemu -qq
  - cd `mktemp -d`
  - mkdir -p ${GOPATH}/src/github.com/hyperhq
  - git clone https://github.com/hyperhq/runv.git ${GOPATH}/src/github.com/hyperhq/runv
  - wget https://git.fedorahosted.org/cgit/lvm2.git/snapshot/lvm2-2_02_131.tar.xz
  - tar xf lvm2-2_02_131.tar.xz
  - cd lvm2-2_02_131
  - ./configure && make device-mapper && sudo make install

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - ./verify-gofmt.sh
  - ./autogen.sh
  - ./configure 
  - make
  - hack/test-cmd.sh

